import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
    en: {
        translation: {
            nav: {
                home: 'Home',
                about: 'About',
                audit: 'Audit',
                settings: 'Settings',
                login: 'Login',
                logout: 'Logout'
            },
            buttons: {
                save: 'Save',
                cancel: 'Cancel',
                submit: 'Submit',
                back: 'Back',
                previous: 'Previous',
                next: 'Next',
                finish: 'Finish',
                start: 'Start',
                add: 'Add',
                generating: 'Generating Report...',
                newAudit: 'New Audit',
                print: 'Print Report'
            },
            languages: {
                en: 'English',
                fr: 'Français',
                ar: 'العربية'
            },
            titles: {
                main: 'AI Maturity Audit'
            },
            subtitle: 'AI maturity assessment framework — 6 axes of analysis',
            features: {
                axisTitle: '6 Axes of Analysis',
                axisDesc: 'Evaluate your organization across 6 key dimensions: Strategy, Data, Technologies, Governance, Culture and Infrastructure.',
                recommendationsTitle: 'AI Recommendations',
                recommendationsDesc: 'Receive personalized AI-driven recommendations to optimize your AI strategy.',
                roadmapTitle: 'Roadmap',
                roadmapDesc: 'Get a comprehensive analysis and a personalized roadmap to progress and identify strengths and opportunities.'
            },
            cta: {
                subtitle: 'Free audit • Instant results • No signup required'
            },
            question: {
                progress: 'Question {{current}} of {{total}}'
            },
            
            personal: {
            title: 'Personal information',
            subtitle: 'Provide your contact details to receive a full report',
            fullName: 'Full name',
            companyName: 'Company name',
            sector: 'Sector',
            size: 'Company size',
            phone: 'Phone number',
            email: 'Email',
            thanksTitle: 'Thank you!',
            thanksMessage: 'Your responses have been recorded. We will contact you shortly.',
            sizePlaceholder: 'Select company size',
            sizeOptions: {
                s1: '1-10 employees',
                s2: '11-50 employees',
                s3: '51-200 employees',
                s4: '201-1000 employees',
                s5: '1000+ employees'
            }
        },
        report: {
            title: 'AI Maturity Report',
            auditLabel: 'Audit Report',
            maturityLabel: 'Maturity Level',
            scoreLabel: 'Score',
            evaluationByAxis: 'Evaluation by Axis',
            globalAnalysisTitle: 'Global Analysis',
            generating: 'Generating your personalized AI maturity report... This may take a moment.',
            executiveSummaryLabel: 'Executive Summary',
            roadmapTitle: 'Roadmap',
            actionsPrioritaires: 'Priority actions',
            generatedBy: 'Generated by AI Crafters',
            strengthsTitle: 'Strengths',
            weaknessesTitle: 'Weaknesses',
            roadmap6MonthsTitle: '6-Month Roadmap',
            roadmap12MonthsTitle: '12-Month Roadmap',
            recommendationsTitle: 'Key Recommendations'
        },
        maturity: {
            initial: 'Initial',
            beginner: 'Beginner',
            intermediate: 'Intermediate',
            advanced: 'Advanced',
            excellence: 'Excellence'
        }
    }
},
    fr: {
        translation: {
            nav: {
                home: 'Accueil',
                about: 'À propos',
                audit: 'Audit',
                settings: 'Paramètres',
                login: 'Connexion',
                logout: 'Se déconnecter'
            },
            buttons: {
                save: 'Enregistrer',
                cancel: 'Annuler',
                submit: 'Soumettre',
                back: 'Retour',
                previous: 'PRÉCÉDENT',
                next: 'SUIVANT',
                finish: 'TERMINER',
                start: "Commencer l'Audit",
                add: 'Ajouter',
                generating: 'Génération du rapport...',
                newAudit: 'Nouvel Audit',
                print: 'Imprimer le Rapport'
            },
            languages: {
                en: 'English',
                fr: 'Français',
                ar: 'العربية'
            },
            titles: {
                main: "Audit de Maturité IA"
            },
            subtitle: "Framework d'évaluation de la maturité IA - 6 axes d'analyse",
            features: {
                axisTitle: '6 Axes d\'Analyse',
                axisDesc: "Évaluez votre organisation à travers 6 dimensions clés : Stratégie, Data, Technologies, Gouvernance, Culture et Infrastructure.",
                recommendationsTitle: 'Recommandations IA',
                recommendationsDesc: "Recevez des recommandations personnalisées basées sur l'intelligence artificielle pour optimiser votre stratégie IA.",
                roadmapTitle: 'Feuille de Route',
                roadmapDesc: "Obtenez une analyse complète et une feuille de route personnalisée pour progresser et identifier vos forces et opportunités."
            },
            cta: {
                subtitle: 'Audit gratuit • Résultats instantanés • Aucune inscription requise'
            },
            question: {
                progress: 'Question {{current}} de {{total}}'
            },
            personal: {
                title: 'Informations personnelles',
                subtitle: 'Fournissez vos coordonnées pour recevoir le rapport complet',
                fullName: 'Nom complet',
                companyName: 'Nom de l\'entreprise',
                sector: 'Secteur',
                size: 'Taille de l\'entreprise',
                phone: 'Numéro de téléphone',
                email: 'Email',
                thanksTitle: 'Merci !',
                thanksMessage: 'Vos réponses ont été enregistrées. Nous vous contacterons sous peu.',
                sizePlaceholder: 'Sélectionnez la taille de l\'entreprise',
                sizeOptions: {
                    s1: '1-10 employés',
                    s2: '11-50 employés',
                    s3: '51-200 employés',
                    s4: '201-1000 employés',
                    s5: '1000+ employés'
                }
            },
            report: {
                title: 'Rapport de Maturité IA',
                auditLabel: 'Rapport d\'Audit',
                maturityLabel: 'Niveau de Maturité',
                scoreLabel: 'Score',
                evaluationByAxis: 'Évaluation par Axe',
                globalAnalysisTitle: 'Analyse Globale',
                generating: 'Génération de votre rapport personnalisé de maturité IA en cours... Cela peut prendre un moment.',
                executiveSummaryLabel: 'Résumé Exécutif',
                roadmapTitle: 'Feuille de Route',
                actionsPrioritaires: 'Actions Prioritaires',
                generatedBy: 'Généré par AI Crafters',
                strengthsTitle: 'Forces',
                weaknessesTitle: 'Faiblesses',
                roadmap6MonthsTitle: 'Feuille de Route 6 Mois',
                roadmap12MonthsTitle: 'Feuille de Route 12 Mois',
                recommendationsTitle: 'Recommandations Clés'
            },
            maturity: {
                initial: 'Initial',
                beginner: 'Débutant',
                intermediate: 'Intermédiaire',
                advanced: 'Avancé',
                excellence: 'Excellence'
            }
        }
    },
    ar: {
        translation: {
            nav: {
                home: 'الرئيسية',
                about: 'حول',
                audit: 'تدقيق',
                settings: 'الإعدادات',
                login: 'تسجيل الدخول',
                logout: 'تسجيل الخروج'
            },
            buttons: {
                save: 'حفظ',
                cancel: 'إلغاء',
                submit: 'إرسال',
                back: 'رجوع',
                previous: 'السابق',
                next: 'التالي',
                finish: 'إنهاء',
                start: 'ابدأ التدقيق',
                add: 'إضافة',
                generating: 'جاري إنشاء التقرير...',
                newAudit: 'تدقيق جديد',
                print: 'طباعة التقرير'
            },
            languages: {
                en: 'English',
                fr: 'Français',
                ar: 'العربية'
            },
            titles: {
                main: 'تقييم نضج الذكاء الاصطناعي'
            },
            subtitle: 'إطار تقييم نضج الذكاء الاصطناعي - ٦ محاور تحليل',
            features: {
                axisTitle: '٦ محاور تحليل',
                axisDesc: 'قيّم مؤسستك عبر ٦ أبعاد أساسية: الإستراتيجية، البيانات، التكنولوجيا، الحوكمة، الثقافة والبنية التحتية.',
                recommendationsTitle: 'توصيات الذكاء الاصطناعي',
                recommendationsDesc: 'احصل على توصيات مخصصة مدعومة بالذكاء الاصطناعي لتحسين استراتيجيتك في الذكاء الاصطناعي.',
                roadmapTitle: 'خريطة الطريق',
                roadmapDesc: 'احصل على تحليل شامل وخريطة طريق مخصصة للتقدم وتحديد نقاط القوة والفرص.'
            },
            cta: {
                subtitle: 'تدقيق مجاني • نتائج فورية • لا يلزم تسجيل'
            },
            question: {
                progress: 'السؤال {{current}} من {{total}}'
            },
            personal: {
                title: 'المعلومات الشخصية',
                subtitle: 'قدّم معلومات الاتصال الخاصة بك للحصول على التقرير الكامل',
                fullName: 'الاسم الكامل',
                companyName: 'اسم الشركة',
                sector: 'القطاع',
                size: 'حجم الشركة',
                phone: 'رقم الهاتف',
                email: 'البريد الإلكتروني',
                thanksTitle: 'شكراً لك!',
                thanksMessage: 'تم تسجيل إجاباتك. سنتواصل معك قريبًا.',
                sizePlaceholder: 'اختر حجم الشركة',
                sizeOptions: {
                    s1: '1-10 موظفين',
                    s2: '11-50 موظفين',
                    s3: '51-200 موظفين',
                    s4: '201-1000 موظفين',
                    s5: '1000+ موظفين'
                }
            },
            report: {
                title: 'تقرير نضج الذكاء الاصطناعي',
                auditLabel: 'تقرير التدقيق',
                maturityLabel: 'مستوى النضج',
                scoreLabel: 'الدرجة',
                evaluationByAxis: 'تحليل حسب المحاور',
                globalAnalysisTitle: 'التحليل العام',
                generating: 'جاري إنشاء تقرير نضج الذكاء الاصطناعي المخصص لك... قد يستغرق هذا لحظة من الوقت.',
                executiveSummaryLabel: 'الملخص التنفيذي',
                strengthsTitle: 'نقاط القوة',
                weaknessesTitle: 'نقاط الضعف',
                roadmapTitle: 'خريطة الطريق',
                actionsPrioritaires: 'إجراءات أولية',
                generatedBy: 'تم إنشاؤه بواسطة الكرافترز',
                roadmap6MonthsTitle: 'خريطة الطريق 6 أشهر',
                roadmap12MonthsTitle: 'خريطة الطريق 12 شهر',
                recommendationsTitle: 'التوصيات الرئيسية'
            },

            maturity: {
                initial: 'أولي',
                beginner: 'مبتدئ',
                intermediate: 'متوسط',
                advanced: 'متقدم',
                excellence: 'التميز'
            }
        }
    }
}
// Determine initial language (persisted or default)
const initialLang = (typeof window !== 'undefined' && localStorage.getItem('lang')) || 'en'

i18n.use(initReactI18next).init({
    resources,
    lng: initialLang,
    fallbackLng: 'en',
    interpolation: {
        escapeValue: false // react already safes from xss
    }
})

// Set document attributes and persist when language changes
if (typeof document !== 'undefined') {
    document.documentElement.lang = i18n.language
    document.documentElement.dir = (i18n.language && i18n.language.startsWith('ar')) ? 'rtl' : 'ltr'
}

i18n.on('languageChanged', (lng) => {
    if (typeof document !== 'undefined') {
        document.documentElement.lang = lng
        document.documentElement.dir = (lng && lng.startsWith('ar')) ? 'rtl' : 'ltr'
    }
    if (typeof window !== 'undefined') localStorage.setItem('lang', lng)
})

// Helper to get text direction for layout changes (useful for Arabic RTL)
export const getDirection = (lang?: string) => {
    const l = lang || i18n.language
    return l && l.startsWith('ar') ? 'rtl' : 'ltr'
}

export default i18n
